"""
@author: sourabh garg
Some noun words classied according to their declension type
"""
import itertools
a_stem_masculine=['राम','देव','बाल','बालक','नर','सिंह','जन','गज','अश्व','घट','कूप','भ्रमर',
                  'खग','छात्र','सागर','रोष','रन','ज्वर','व्याघ्र','वृक्ष','भ्रम','धीवर','क्रोध','देह',
                  'नापित','मूषक','सुत','सर्प']
i_stem_masculine=['गिरि','हरि','रवि','कवि','अरि','असि','निधि','कपि','पाणि','विधि','अतिथि','भूपति','अग्नि',
                  'रश्मि','तिथि','सारथि','अद्रि','पति','कवि','मुनि','सुरपति','नृपति','श्रीपति','महीपति','ऋषि','व्याधि']
u_stem_masculine=['गुरु','साधु','शिशु','शम्भु','विष्णु','अभिमन्यु','पशु','केतु','सिन्धु','मन्यु','विधु','भानु','सूनु','वायु',
                  'प्रभु','जानु','वाहु','सेतु','तरु','इषु','सुधांशु','शुभ्रांशु','ऋतु','इक्षु','शत्रु','तन्तु','बिन्धु','बन्धु']
r_stem_masculine=['पितृ','कर्तृ','दातृ','भ्रातृ','वक्तृ','पोतृ','भर्तृ','होतृ','नप्तृ','देवृ','जामातृ']
o_stem_masculine=['गो']
a_stem_feminine=['रमा','बालिका','लता','कमला','सरला','निर्मला','आशा','दुर्गा','विद्या','दया','कृपा',
                 'गंगा','कथा','माला','कोकिला','वाटिका','नासिका','प्रभा','शाला','कन्या','कला']
i_stem_feminine=['मति','भक्ति','बुद्धि','प्रीति','स्तुति','श्रुति','धृति','स्मृति','कीर्ति','कान्ति',
                 'जाति','मुक्ति','शक्ति','आकृति','हानि','रीति','भूमि','रूचि','दृष्टि','सृष्टि',
                 'संपत्ति','वृद्धि','नीति','शुद्धि','रात्रि','वृष्टि']
ii_stem_feminine=['नदी','काशी','गौरी','पार्वती','लक्ष्मी','काली','भवानी','तरी','तन्त्री','कुमारी',
                  'नारी','जननी','नगरी','दासी','पृथ्वी','मैत्री','श्रेणी','पुत्री','धात्री','भागीरथी',
                  'स्त्री','श्री','सिंही','वाणी','पत्नी','सखी','देवी','वाराणसी','भगिनी']
u_stem_feminine=['धेनु','तनु','हनु','रज्जु','रेणु','चञ्चु']
uu_stem_feminine=['वधू','जम्बू','श्मश्रू']
r_stem_feminine=['मातृ','स्वसृ','दुहितृ','यातृ','ननान्दृ']
oo_stem_feminine=['नौ']
a_stem_neuter=['फल','गृह','नगर','पुस्तक','सुख','खान','नेत्र','मुख','श्रोत्र','चिबुक','उदर','नेपथ्य','कपूर','धन',
               'वन','जल','मित्र','शरीर','वस्त्र','पुष्प','पाप','पुण्य','चक्र','कार्य','पत्र','सत्य','ज्ञान','नवनीत',
               'विष','गीत','कमल','आम्र','मुख']
i_stem_neuter=['वारि','दधि','अस्थि','अक्षि']
u_stem_neuter=['मधु','अश्रु','वसु','जानु','वस्तु','दारु','श्यश्रु']
r_stem_neuter=['कर्तृ','धातृ','ज्ञातृ']

n_stem_masculine=['राजन्','आत्मन्']
t_stem_masculine=['भगवत्','भवत्','गतवत्']
s_stem_masculine=['विद्वस्','चन्द्रमस्']
t_stem_feminine=['सरित्']
c_stem_feminine=['वाच्']
sh_stem_feminine=['दिश्']
h_stem_feminine=['उपानह्']
dh_stem_feminine=['क्षुध्']
t_stem_neuter=['जगत्']
s_stem_neuter=['पयस्']


all_noun=[a_stem_masculine,i_stem_masculine,u_stem_masculine,r_stem_masculine,o_stem_masculine,
          a_stem_feminine,i_stem_feminine,ii_stem_feminine,u_stem_feminine,uu_stem_feminine,r_stem_feminine,oo_stem_feminine,
          a_stem_neuter,i_stem_neuter,u_stem_neuter,r_stem_neuter,
          n_stem_masculine,t_stem_masculine,s_stem_masculine,t_stem_feminine,c_stem_feminine,sh_stem_feminine,h_stem_feminine,dh_stem_feminine,t_stem_neuter,s_stem_neuter]
dict_noun={0:'a_stem_masculine',
           1:'i_stem_masculine',
           2:'u_stem_masculine',
           3:'r_stem_masculine',
           4:'o_stem_masculine',
           5:'a_stem_feminine',
           6:'i_stem_feminine',
           7:'ii_stem_feminine',
           8:'u_stem_feminine',
           9:'uu_stem_feminine',
           10:'r_stem_feminine',
           11:'oo_stem_feminine',
           12:'a_stem_neuter',
           13:'i_stem_neuter',
           14:'u_stem_neuter',
           15:'r_stem_neuter',
           16:'n_stem_masculine',
           17:'t_stem_masculine',
           18:'s_stem_masculine',
           19:'t_stem_feminine',
           20:'c_stem_feminine',
           21:'sh_stem_feminine',
           22:'h_stem_feminine',
           23:'dh_stem_feminine',
           24:'t_stem_neuter',
           25:'s_stem_neuter'}
pronoun=['अस्मद्','युष्मद्','यत्','तत्','एतत्','किम्','भवत्','सर्व','इदम्']